### ISSUE TITLE
week 01  回覆

### ISSUE THREAD

**Issue by azole** [110306075/git-practice#1]
洪昇，希望你坦誠回答這一題，這份作業是你自己寫的，還是有透過 AI 協助呢？ 

另外，以下這句話是什麼意思？
> 如果檢出某個 commit，HEAD 會指向該 commit，稱為「分離頭指針」（detached HEAD）。

**Comment by 110306075** [comment]
> 洪昇，希望你坦誠回答這一題，這份作業是你自己寫的，還是有透過 AI 協助呢？
> 
> 另外，以下這句話是什麼意思？
> 
> > 
老師好，這份作業在課程期許與影片心得我是重新看過課程大綱與影片後，整理本人心得、觀點，最後使用生成式AI幫我通順語句。

在git的作業，我是上網在survey後，整理出重點，然後使用生成式組織文字，若以後有使用生成式AI協作，我會特加註明，並保持自己的原創性與品質。

如果檢出某個 commit，HEAD 會指向該 commit，稱為「分離頭指針」（detached HEAD）。 ->這句話當時沒有表達清楚，當時要表達的情境是一般情況下在分支上時，分支的指針與HEAD指針會現在綁定的狀態，但當例如checkout某一版本的commit時，會有HEAD指針與分支指針會分離，這是我在寫作業survey時在中國的技術部落格所看到的資訊。

**Comment by azole** [comment]
收到，那你可能反而不要用 AI 來幫你潤飾... 或是要調整你的 prompt，整個內容 AI 感非常重，對你來說可能會是扣分。 

無論是跟 AI 協作或是看簡中文件，我覺得都是可以的，我也會這樣做，畢竟 AI 真的很好用、像是讀過全世界的書一樣（雖然讀的不算好），而中國人的人口基數，加上競爭，他們確實也產出了非常多的文件，甚至有些深入一點的資料還只有簡中有。所以這些都無妨，我並不會影響對你評價。

但是，對，但是來了，根據你目前呈現的結果，你可能會需要練習寫作，練習用自己的風格跟說明方式去表達，例如你這次寫的「分支的指針與HEAD指針會現在綁定的狀態」這句的「現」這個字是不是有點多了？ 我們不是文學作家，不需要華麗的辭藻，但要通順、要確保閱讀的人知道你想要表達什麼，這點我也都還在學習。

我個人使用 AI 的方式會是利用他來幫我找靈感，他產生出來的東西，我盡可能不直接用，但會利用他學習、找靈感後，用自己的話來說明與寫作。

作業的目的除了技術本身外，我也會關注大家的軟技能，如同上一節課所說的，技術能力要合格，也要懂得表現出來，加油。

**Comment by 110306075** [comment]
> 收到，那你可能反而不要用 AI 來幫你潤飾... 或是要調整你的 prompt，整個內容 AI 感非常重，對你來說可能會是扣分。
> 
> 無論是跟 AI 協作或是看簡中文件，我覺得都是可以的，我也會這樣做，畢竟 AI 真的很好用、像是讀過全世界的書一樣（雖然讀的不算好），而中國人的人口基數，加上競爭，他們確實也產出了非常多的文件，甚至有些深入一點的資料還只有簡中有。所以這些都無妨，我並不會影響對你評價。
> 
> 但是，對，但是來了，根據你目前呈現的結果，你可能會需要練習寫作，練習用自己的風格跟說明方式去表達，例如你這次寫的「分支的指針與HEAD指針會現在綁定的狀態」這句的「現」這個字是不是有點多了？ 我們不是文學作家，不需要華麗的辭藻，但要通順、要確保閱讀的人知道你想要表達什麼，這點我也都還在學習。
> 
> 我個人使用 AI 的方式會是利用他來幫我找靈感，他產生出來的東西，我盡可能不直接用，但會利用他學習、找靈感後，用自己的話來說明與寫作。
> 
> 作業的目的除了技術本身外，我也會關注大家的軟技能，如同上一節課所說的，技術能力要合格，也要懂得表現出來，加油。

了解，謝謝老師，我剛剛重新看過作業也發現到我在寫作時沒有留意到讀者的感受與想法，“我盡可能不直接用，但會利用他學習、找靈感後，用自己的話來說明與寫作。”我將來試著會使用這樣的概念來與生成式AI協作，謝謝老師指教。

**Comment by azole** [comment]
我們彼此的討論沒有問題後，你就可以 close 這個 issue。
